### ISSUE TITLE
Error logs upon startup

### ISSUE THREAD

**Issue by Reshy** [lilypuree/ConnectibleChains#8]
[07:37:15] [Thread-0/ERROR]: Exception caught during firing event: Cannot invoke "com.lilypuree.connectiblechains.client.render.entity.ChainKnotEntityRenderer.getChainRenderer()" because "com.lilypuree.connectiblechains.client.ClientEventHandler.chainKnotEntityRenderer" is null
	Index: 1
	Listeners:
		0: NORMAL
		1: ASM: class com.lilypuree.connectiblechains.client.ClientEventHandler onClientConfigReload(Lnet/minecraftforge/fml/event/config/ModConfigEvent$Reloading;)V
java.lang.NullPointerException: Cannot invoke "com.lilypuree.connectiblechains.client.render.entity.ChainKnotEntityRenderer.getChainRenderer()" because "com.lilypuree.connectiblechains.client.ClientEventHandler.chainKnotEntityRenderer" is null
	at TRANSFORMER/connectiblechains@2.1.0/com.lilypuree.connectiblechains.client.ClientEventHandler.onClientConfigReload(ClientEventHandler.java:45)
	at net.minecraftforge.eventbus.ASMEventHandler_164_ClientEventHandler_onClientConfigReload_Reloading.invoke(.dynamic)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at LAYER PLUGIN/javafmllanguage@1.18.2-40.1.0/net.minecraftforge.fml.javafmlmod.FMLModContainer.lambda$new$0(FMLModContainer.java:41)
	at LAYER PLUGIN/fmlcore@1.18.2-40.1.0/net.minecraftforge.fml.ModContainer.lambda$dispatchConfigEvent$7(ModContainer.java:135)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at LAYER PLUGIN/fmlcore@1.18.2-40.1.0/net.minecraftforge.fml.ModContainer.dispatchConfigEvent(ModContainer.java:135)
	at LAYER PLUGIN/fmlcore@1.18.2-40.1.0/net.minecraftforge.fml.config.ModConfig.fireEvent(ModConfig.java:77)
	at LAYER PLUGIN/fmlcore@1.18.2-40.1.0/net.minecraftforge.fml.config.ConfigFileTypeHandler$ConfigWatcher.run(ConfigFileTypeHandler.java:147)
	at MC-BOOTSTRAP/com.electronwill.nightconfig.core@3.6.4/com.electronwill.nightconfig.core.file.FileWatcher$WatcherThread.run(FileWatcher.java:181)

[07:37:15] [Thread-0/ERROR]: Exception caught during firing event: Cannot invoke "com.lilypuree.connectiblechains.client.render.entity.ChainKnotEntityRenderer.getChainRenderer()" because "com.lilypuree.connectiblechains.client.ClientEventHandler.chainKnotEntityRenderer" is null
	Index: 1
	Listeners:
		0: NORMAL
		1: ASM: class com.lilypuree.connectiblechains.client.ClientEventHandler onClientConfigReload(Lnet/minecraftforge/fml/event/config/ModConfigEvent$Reloading;)V
java.lang.NullPointerException: Cannot invoke "com.lilypuree.connectiblechains.client.render.entity.ChainKnotEntityRenderer.getChainRenderer()" because "com.lilypuree.connectiblechains.client.ClientEventHandler.chainKnotEntityRenderer" is null
	at TRANSFORMER/connectiblechains@2.1.0/com.lilypuree.connectiblechains.client.ClientEventHandler.onClientConfigReload(ClientEventHandler.java:45)
	at net.minecraftforge.eventbus.ASMEventHandler_164_ClientEventHandler_onClientConfigReload_Reloading.invoke(.dynamic)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at LAYER PLUGIN/javafmllanguage@1.18.2-40.1.0/net.minecraftforge.fml.javafmlmod.FMLModContainer.lambda$new$0(FMLModContainer.java:41)
	at LAYER PLUGIN/fmlcore@1.18.2-40.1.0/net.minecraftforge.fml.ModContainer.lambda$dispatchConfigEvent$7(ModContainer.java:135)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at LAYER PLUGIN/fmlcore@1.18.2-40.1.0/net.minecraftforge.fml.ModContainer.dispatchConfigEvent(ModContainer.java:135)
	at LAYER PLUGIN/fmlcore@1.18.2-40.1.0/net.minecraftforge.fml.config.ModConfig.fireEvent(ModConfig.java:77)
	at LAYER PLUGIN/fmlcore@1.18.2-40.1.0/net.minecraftforge.fml.config.ConfigFileTypeHandler$ConfigWatcher.run(ConfigFileTypeHandler.java:147)
	at MC-BOOTSTRAP/com.electronwill.nightconfig.core@3.6.4/com.electronwill.nightconfig.core.file.FileWatcher$WatcherThread.run(FileWatcher.java:181)

**Comment by lilypuree** [comment]
can you upload the full error log

**Comment by Reshy** [comment]
Unfortunately, I can't locate the original log, it's been lost among all the noise over the past four months.

**Comment by lilypuree** [comment]
The new update might solve this issue

**Comment by lilypuree** [comment]
On double checking, this issue will not happen again.
